site_name: PyTrendy

nav:
  - Home: index.md
  - Example Gallery:
    - Overview: examples/index.md
    - Fundamentals: 
      - Gradual: examples/gradual.ipynb
      - Abrupt: examples/abrupt.ipynb
      - Noise: examples/noise.md
  - API Reference: reference

theme: 
  name: material # flatly, material, minty
  font:
    text: Roboto
  logo: icon.png
  favicon: icon.png
  features:
    - navigation.indexes
    - content.tabs.link
    - content.code.copy
    - header.autohide
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

markdown_extensions:
  - tables
  - codehilite:
      guess_lang: false
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - markdown.extensions.admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html

plugins:
  - offline
  - search
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_section_style: list # or "table"
            docstring_style: "google"
            filters: ["!^_"]
            heading_level: 1
            merge_init_into_class: true
            parameter_headings: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false 
            show_signature_annotations: false
            summary: false
            reload: true
            paths: ['.']   # <-- tell it where to load from
  - api-autonav:
      modules: ['pytrendy']
      module_options:
        ".*":
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          heading_level: 1
          show_docstring: false
      nav_section_title: "API Reference"
      api_root_uri: "reference"
      nav_item_prefix: "<code class='doc-symbol doc-symbol-nav'></code>" #"<code class='doc-symbol doc-symbol-nav doc-symbol-module'></code>"
      exclude_private: false
      show_full_namespace: false
      on_implicit_namespace_package: "warn"
  - jupyterlite:
      enabled: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RussellSB/pytrendy
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pytrendy

validation:
  links:
    unrecognized_links: ignore

repo_url: https://github.com/RussellSB/pytrendy
repo_name: russellsb/pytrendy
edit_uri: edit/main/docs/
