[project]
name = "pytrendy"
version = "1.2.0.dev4"
description = "Trend Detection in Python. Applicable for real-world industry use cases in time series."
authors = [
    { name = "Russell Sammut Bonnici", email = "r.sammutbonnici@gmail.com" },
    { name = "Barsha Deb", email = "debbarsha1503@gmail.com" }
]
maintainers = [
    { name = "Russell Sammut Bonnici", email = "r.sammutbonnici@gmail.com" },
    { name = "Barsha Deb", email = "debbarsha1503@gmail.com" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "matplotlib"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "pytest-mpl",
    "pytest-timeout"
]
docs = [
    "mkdocs>=1.6,<2",
    "mkdocs-material>=9.7,<10",
    "mkdocs-api-autonav==0.4.0",
    "mkdocstrings>=0.28.3,<1",
    "mkdocstrings-python>=1.16,<2",
    "mkdocs-jupyterlite==0.4.1"
]

[project.urls]
repository = "https://github.com/RussellSB/pytrendy"

[tool.setuptools.packages.find]
where = ["."]
include = ["pytrendy*"]

[tool.pytest.ini_options]
addopts = "--mpl --cov=pytrendy --cov-report=term --cov-report=xml:coverage.xml"
timeout = 15
markers = [
    "core: essential tests that must pass for core functionality",
    "plot: tests for visualization/plotting functionality"
]